### ISSUE TITLE
Use the same PEM files for every Heimdall instance

### ISSUE THREAD

**Issue by qbalsdon** [henrinormak/Heimdall#23]
Good day Henri,

Thank you for responding to my tweet! I am trying to use the same PEM keys for every instance of Heimdall that I create. All I need to do is encrypt a timestamp with the PRIVATE key to make a simple signature. I haver the PEM of the Public key as well if I need it. I do not mind having to re-make the keys, but I definitely need the private key in a PEM format for the Android version (so if I generate a new key in a new format, I will need to make sure I can convert the new key to a PEM format as well). 

Could you please give me an example where the SAME key (preferably a set of PEM keys) are ALWAYS used in Heimdall and result in the same encrypted string? When I do the following:

```
    if let heimdall = Heimdall(tagPrefix: "www.example.com"){
        if let encryptedString = heimdall.encrypt("test") {
            print("Encrption: [\(encryptedString)]")
        } else {
            print("Encryption error")
        }
    } else {
        print("Init error")
    }
```

I get a different String every time. I have tried putting the PEM Strings in as parameters:

```
    if let heim = Heimdall(publicTag: "...", privateTag: "...")
```

but I get the same result - different Strings every time I run it.

**Comment by henrinormak** [comment]
Hi there,

The answer to why the string is always different can be found when reading through the [README](https://github.com/henrinormak/Heimdall#note-on-encryptiondecryption) - in short, it is as expected, as the actual encryption/decryption use AES, rather than the RSA keys directly (the symmetric key is encrypted with RSA). This is not an indication of difference in RSA keys (as they are the same if Heimdall is initialised the way you do it), but it does show that the AES key is different every time.

Regards to extracting the private key, currently Heimdall does not allow extracting the private key, this is a philosophical choice, as I firmly believe that private keys should be device specific and never leave the device, instead systems should support multiple keys for the same user (device specific keys that is). However, as there have been multiple request of the same nature, I have decided to accept a pull-request that adds the necessary code (Heimdall under the sheets has a way to export the private key data, not in PEM format though).

I suggest you look at the data returned by the private function defined [here](https://github.com/henrinormak/Heimdall/blob/master/Heimdall/Heimdall.swift#L488) and create a suitable set of public functions (similar to [these](https://github.com/henrinormak/Heimdall/blob/master/Heimdall/Heimdall.swift#L126-L146) for the private key), it should be a matter of studying the PEM format (which AFAIK is similar to X.509).

Cheers,
Henri

PS! The tags defined in the initialiser are all but informal, they are simply used to distinguish the key pairs and have no effect on the keys themselves.

**Comment by qbalsdon** [comment]
Ah ok I see what you mean. So the AES key changes each time. This means that the server in this case would have to be aware of the AES key as well.

You see, I do not need to know the private key, I have no issue that it is on the device. However my problem is that EVERY instance on all iPhone devices use the SAME private key, as this is an "app signature" for an API. So as long as I can extract the public key as a PEM it would be fine. But it seems that Heimdall will create keys at least "per installation" - which poses a problem for me. 

But anyway thanks for the excellent work! I wish you all the best :)

**Comment by henrinormak** [comment]
I see, do you need to sign the request or actually encrypt it? Signing requires private key, but encryption can be done without a private key. In any case, I suspect that your architecture is not super compatible with Heimdall, especially if you need encryption, as the Heimdall approach to using a combination of RSA and AES is not really standardised and is something I came up with myself (with some inspiration from the web).

All in all, if you think this would be solved by creating a new initialiser that also takes private key data, then I hope the links I provided above are helpful. I would look at this myself, but unfortunately I don't currently have time (and I am not entirely sure this is still appropriate).

**Comment by qbalsdon** [comment]
Hi there,

Unfortunately I need to encrypt it with the private key, this is a "feature" of the API (that I have no control over). I was hoping that Heimdall was the answer to my problem, as my StackOverflow question has gotten no love. I really like the library, but I agree, I do not think (for this app) that the library is what I need.

Kind regards,
Quintin
