### ISSUE TITLE
Add Error Logging

### ISSUE THREAD

**Issue by patgoley** [henrinormak/Heimdall#44]
Anywhere errors might occur it would be nice to log them. I'm currently unable to tell why my call to the failable initializer is returning nil.

**Comment by henrinormak** [comment]
Perhaps a better solution would be to make those initialisers throwable instead? That way it will be up to the user how to handle the errors (including the possibility of ignoring them as is done now). When I originally wrote Heimdall, Swift's error model was not there, so it might be better to revisit the entire initialiser concept, rather than to simply bolt on logging.

**Comment by patgoley** [comment]
Hey thanks for the feedback, I think throwing is a great idea especially if we can map the OSStatus values to something more informative.

I actually figured out what my problem was. I was calling the wrong init, `init(publicTag:publicKeyData)` when I meant to call `init(tagPrefix:keySize)`. I mistook them because both functions have a string param and the second params have default values, so my fault there, but if it threw I would've figured it out much quicker I think. 

I'll take some time later today and update my PR with some attempts at throwing. Either way, great framework! You've saved me tons of time already!
