### ISSUE TITLE
Update for Swift 3.0

### ISSUE THREAD

**Issue by dmitryPocopay** [henrinormak/Heimdall#48]
Hello, can this be update for the new Swift 3.0?

**Comment by henrinormak** [comment]
I am currently unavailable for active development, but I can try to review PRs, so, if you are willing to make the updates, I can get them reviewedand merged.

**Comment by rajeevpra** [comment]
Hi, I spend few hours and updated it to swift 3.0, if you are willing I can submit PR. I didn't write any new tests but all your test are passing.

**Comment by henrinormak** [comment]
That would be awesome, please do submit a PR!

**Comment by rajeevpra** [comment]
Submitted PR.. Please make sure to run tests on ios 9.x, its failing on 10.x because of the issues being discussed in #47

**Comment by LiborZ** [comment]
I can't be much help with update to Swift 3.0 but hope you can fix it. I really need to upgrade. Thanks

**Comment by rajeevpra** [comment]
It all working, It's failing because of test failure when its trying to run it on ios 10 simulator. This is unrelated to any changes to Swift 3 (see #47, its because of bug in ios10 simulator) , so if any of you can suggest a way to restrict tests to ios9.x in travis-ci. I tried different configurations but nothing seems to be working.

**Comment by rajeevpra** [comment]
Done with test passing for 9.3.

**Comment by LiborZ** [comment]
@henrinormak Can you please merge changes for Swift 3.0? Or at least create branch for Swift 3?

**Comment by henrinormak** [comment]
As I am unable to work on this or even test this, I am taking steps to adding people as collaborators to the project. Track #49 for progress on that front
